import { validateCss, formatIssues } from './tokenizer';
import type { ValidationResult, CssIssue } from './tokenizer';
export { validateCss, formatIssues };
export type { ValidationResult, CssIssue };

const HEADER = '/* Generated by Obsidian CSS Snippet Designer */';

/**
 * Normalise a scope selector. An empty scope means the document root.
 */
function normaliseScope(scope: string): string {
	const trimmed = scope.trim();
	return trimmed.length === 0 ? ':root' : trimmed;
}

/** Normalise a custom-property name, adding the `--` prefix when absent. */
function normaliseVariable(variable: string): string {
	const trimmed = variable.trim();
	return trimmed.startsWith('--') ? trimmed : `--${trimmed}`;
}

/**
 * Byte-order key comparison for deterministic token ordering.
 * CSS identifiers are ASCII, so a plain code-unit comparison is equivalent.
 */
function byKey(a: string, b: string): number {
	return a < b ? -1 : a > b ? 1 : 0;
}

/**
 * In-memory design-token store, keyed by scope selector then custom property.
 *
 * Provides normalised scopes and variables with deterministic sorted output.
 */
export class SnippetEngine {
	private tokens = new Map<string, Map<string, string>>();

	/** Insert or overwrite a token. */
	setToken(scope: string, variable: string, value: string): void {
		const key = normaliseScope(scope);
		let scopeMap = this.tokens.get(key);
		if (!scopeMap) {
			scopeMap = new Map<string, string>();
			this.tokens.set(key, scopeMap);
		}
		scopeMap.set(normaliseVariable(variable), value.trim());
	}

	/** Read a token back, or `undefined` when it is not set. */
	getToken(scope: string, variable: string): string | undefined {
		return this.tokens.get(normaliseScope(scope))?.get(normaliseVariable(variable));
	}

	/** Remove a token, dropping the scope entirely once it holds nothing. */
	removeToken(scope: string, variable: string): void {
		const key = normaliseScope(scope);
		const scopeMap = this.tokens.get(key);
		if (!scopeMap) return;
		scopeMap.delete(normaliseVariable(variable));
		if (scopeMap.size === 0) this.tokens.delete(key);
	}

	/** Number of scopes currently holding at least one token. */
	get scopeCount(): number {
		return this.tokens.size;
	}

	/** Every scope selector currently held, in sorted order. */
	scopes(): string[] {
		return Array.from(this.tokens.keys()).sort(byKey);
	}

	/** Snapshot one scope's tokens as a plain object, in sorted order. */
	scopeTokens(scope: string): Record<string, string> {
		const scopeMap = this.tokens.get(normaliseScope(scope));
		if (!scopeMap) return {};
		const out: Record<string, string> = {};
		for (const key of Array.from(scopeMap.keys()).sort(byKey)) {
			out[key] = scopeMap.get(key) as string;
		}
		return out;
	}

	/** Discard all tokens. */
	clear(): void {
		this.tokens.clear();
	}

	/**
	 * Serialise every scope to CSS, sorted for deterministic output so that
	 * saving twice without changes produces an identical file.
	 */
	exportCss(): string {
		let out = `${HEADER}\n\n`;
		for (const scope of this.scopes()) {
			const scopeMap = this.tokens.get(scope);
			if (!scopeMap || scopeMap.size === 0) continue;
			out += `${scope} {\n`;
			for (const variable of Array.from(scopeMap.keys()).sort(byKey)) {
				out += `  ${variable}: ${scopeMap.get(variable) as string};\n`;
			}
			out += '}\n\n';
		}
		return out;
	}

	/** Structural check of this engine's own output. */
	validate(): ValidationResult {
		return validateCss(this.exportCss());
	}

	/**
	 * Explicitly drop the token state during view teardown.
	 */
	dispose(): void {
		this.clear();
	}
}

/**
 * A stylesheet plus a set of pending per-selector overrides.
 *
 * Construction validates the incoming CSS, so malformed input is rejected up
 * front rather than being silently written back to disk.
 */
export class SnippetSession {
	private readonly initialCss: string;
	private overrides = new Map<string, Map<string, string>>();

	constructor(css: string) {
		const result = validateCss(css);
		if (!result.ok) {
			throw new Error(`CSS Parse Error:\n${formatIssues(result.issues)}`);
		}
		this.initialCss = css;
	}

	/** Create a session, returning `null` instead of throwing on invalid CSS. */
	static tryCreate(css: string): SnippetSession | null {
		try {
			return new SnippetSession(css);
		} catch {
			return null;
		}
	}

	/** Queue a declaration to be appended for `selector`. */
	setProperty(selector: string, property: string, value: string): void {
		let block = this.overrides.get(selector);
		if (!block) {
			block = new Map<string, string>();
			this.overrides.set(selector, block);
		}
		block.set(property, value);
	}

	/** Just the override rules, for injecting as a live preview stylesheet. */
	generateLiveOverrideCss(): string {
		let out = '';
		for (const selector of Array.from(this.overrides.keys()).sort(byKey)) {
			const block = this.overrides.get(selector);
			if (!block || block.size === 0) continue;
			out += `${selector} {\n`;
			for (const property of Array.from(block.keys()).sort(byKey)) {
				out += `  ${property}: ${block.get(property) as string};\n`;
			}
			out += '}\n';
		}
		return out;
	}

	/** The original stylesheet with the overrides appended. */
	serializeFull(): string {
		let merged = this.initialCss;
		if (merged.length > 0 && !merged.endsWith('\n')) merged += '\n';
		return merged + this.generateLiveOverrideCss();
	}
}
