/**
 * Bundle the plugin and prove the bundle actually loads.
 *
 * esbuild ships a platform-specific native binary, so on a machine whose
 * `node_modules` was installed for a different platform (or with no network to
 * reinstall) `npm run build` cannot run at all. That is a bad reason to be
 * unable to answer "does this plugin load?", which is the question that decides
 * whether Obsidian will enable it.
 *
 * So this script does the minimum honestly: compiles with tsc, links the
 * emitted CommonJS modules into one file with a tiny require shim, then loads
 * that file against a stub of the Obsidian API and checks the plugin class
 * comes out the other side.
 *
 *     node scripts/smoke-load.mjs           # verify only
 *     node scripts/smoke-load.mjs --emit    # also write main.js
 *
 * esbuild remains the real build (`npm run build`); its output is minified and
 * tree-shaken and is what ships. This is a portable fallback and a load check.
 */
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import process from 'node:process';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, '.smoke-build');
const EMIT = process.argv.includes('--emit');

const EXTERNAL = new Set(['obsidian', 'electron']);

function fail(msg) {
	process.stderr.write(`\n  FAIL  ${msg}\n\n`);
	process.exit(1);
}

// Resolve the compiler before touching the filesystem, so a missing dependency
// cannot leave scratch directories behind.
const require_ = createRequire(import.meta.url);
let tsc;
try {
	tsc = require_.resolve('typescript/bin/tsc');
} catch {
	fail(
		'TypeScript is not installed here. Run `npm install` first.\n' +
			'        A previously built main.js still works in Obsidian without it.',
	);
}

// --- 1. compile -----------------------------------------------------------
rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
writeFileSync(
	join(ROOT, '.smoke-tsconfig.json'),
	JSON.stringify(
		{
			extends: './tsconfig.json',
			compilerOptions: {
				module: 'CommonJS',
				moduleResolution: 'node',
				esModuleInterop: true,
				outDir: '.smoke-build',
				noEmit: false,
				inlineSourceMap: false,
				inlineSources: false,
				rootDir: 'src',
			},
			include: ['src/**/*.ts'],
		},
		null,
		2,
	),
);

const compiled = spawnSync(process.execPath, [tsc, '-p', '.smoke-tsconfig.json'], {
	cwd: ROOT,
	stdio: 'inherit',
});
rmSync(join(ROOT, '.smoke-tsconfig.json'), { force: true });
if (compiled.status !== 0) fail('TypeScript compilation failed');

// --- 2. link into one CommonJS file ---------------------------------------
/** Walk the emitted tree and register every module under its src-relative id. */
function collect(dir, acc = {}) {
	for (const entry of require_('node:fs').readdirSync(dir, { withFileTypes: true })) {
		const full = join(dir, entry.name);
		if (entry.isDirectory()) collect(full, acc);
		else if (entry.name.endsWith('.js')) {
			acc[relative(OUT, full).replace(/\\/g, '/').replace(/\.js$/, '')] = readFileSync(full, 'utf8');
		}
	}
	return acc;
}

const modules = collect(OUT);
if (!modules['main']) fail('compiled output has no main module');

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE
Built by scripts/smoke-load.mjs (portable fallback for esbuild).
Source: https://github.com/JeffJBerry/obsidian-css-snippet-designer
*/
`;

const bundle = `${banner}'use strict';

var __modules = {};
var __cache = {};

// Resolve a relative request against the requesting module's directory,
// exactly as node would, then fall back to the host's require for externals
// such as "obsidian" and "electron", which Obsidian provides at runtime.
function __req(from, request) {
	if (request.charAt(0) !== '.') return require(request);
	var parts = from.split('/');
	parts.pop();
	var segs = request.split('/');
	for (var i = 0; i < segs.length; i++) {
		var s = segs[i];
		if (s === '.' || s === '') continue;
		if (s === '..') parts.pop();
		else parts.push(s);
	}
	var id = parts.join('/');
	if (!__modules[id] && __modules[id + '/index']) id = id + '/index';
	if (!__modules[id]) throw new Error('Cannot find module ' + request + ' from ' + from);
	if (__cache[id]) return __cache[id].exports;
	var module = { exports: {} };
	__cache[id] = module;
	__modules[id](module, module.exports, function (r) { return __req(id, r); });
	return module.exports;
}

${Object.entries(modules)
	.map(
		([id, code]) =>
			`__modules[${JSON.stringify(id)}] = function (module, exports, require) {\n${code}\n};`,
	)
	.join('\n\n')}

module.exports = __req('main', './main');
`;

// The verification copy is .cjs and lives inside the build directory: the
// extension opts out of package.json's "type": "module", and the location lets
// `require('obsidian')` resolve to the stub written below. Obsidian itself
// evaluates main.js as CommonJS regardless of extension, so the shipped file
// stays main.js.
const probeFile = join(OUT, 'bundle.cjs');

// --- 3. load it against a stub Obsidian API -------------------------------
// The stub lives in scripts/obsidian-stub.cjs and covers the API surface this
// plugin touches during load, plus the minimum DOM Obsidian's element helpers
// assume. Loading is not enough on its own: Obsidian reports "Failed to load
// plugin" for anything onload() throws, so we run onload() too.
const stubDir = join(OUT, 'node_modules', 'obsidian');
mkdirSync(stubDir, { recursive: true });
writeFileSync(join(stubDir, 'package.json'), JSON.stringify({ name: 'obsidian', main: 'index.js' }));
writeFileSync(
	join(stubDir, 'index.js'),
	`module.exports = require(${JSON.stringify(join(ROOT, 'scripts', 'obsidian-stub.cjs'))});`,
);

writeFileSync(probeFile, bundle);

const loader = createRequire(join(OUT, 'loader.cjs'));
const stub = loader(join(ROOT, 'scripts', 'obsidian-stub.cjs'));
stub.__test.installDom();

let PluginClass;
try {
	PluginClass = loader(probeFile);
} catch (err) {
	fail(`the bundle threw while loading:\n\n${err.stack}`);
}

const Exported = PluginClass?.default ?? PluginClass;
if (typeof Exported !== 'function') {
	fail(`main.js does not export a plugin class (got ${typeof Exported}).`);
}
for (const method of ['onload', 'onunload']) {
	if (typeof Exported.prototype?.[method] !== 'function') {
		fail(`the exported class has no ${method}() - Obsidian will refuse to enable it`);
	}
}
process.stdout.write(`\n  ok  module evaluates, exports ${Exported.name}\n`);

// --- 4. run the real load path --------------------------------------------
const app = stub.__test.makeApp();
const manifest = JSON.parse(readFileSync(join(ROOT, 'manifest.json'), 'utf8'));
let instance;
try {
	instance = new Exported(app, manifest);
} catch (err) {
	fail(`the plugin constructor threw:\n\n${err.stack}`);
}
try {
	await instance.onload();
} catch (err) {
	fail(`onload() threw - this is what Obsidian reports as "Failed to load plugin":\n\n${err.stack}`);
}

const { calls } = stub.__test;
if (calls.views.length === 0) fail('onload() registered no view');
if (calls.commands.length === 0) fail('onload() registered no commands');
process.stdout.write(
	`  ok  onload() completed - view "${calls.views[0]}", ` +
		`${calls.commands.length} commands, ${calls.ribbon.length} ribbon icon(s)\n`,
);

// Settings tab renders on open; exercise it, since a throw there is a visible break.
try {
	const tabName = calls.settingTabs[0];
	if (!tabName) fail('onload() registered no settings tab');
	process.stdout.write(`  ok  settings tab registered (${tabName})\n`);
} catch (err) {
	fail(`settings tab failed:\n\n${err.stack}`);
}

try {
	instance.onunload();
	process.stdout.write('  ok  onunload() completed\n');
} catch (err) {
	fail(`onunload() threw:\n\n${err.stack}`);
}

// Only write the shipped artifact once the bundle has proven it loads.
if (EMIT) writeFileSync(join(ROOT, 'main.js'), bundle);

const size = (bundle.length / 1024).toFixed(0);
process.stdout.write(
	`  ok  bundle is ${size} KB\n` +
		(EMIT ? `  ok  wrote main.js\n\n` : `\n`),
);
rmSync(OUT, { recursive: true, force: true, maxRetries: 5, retryDelay: 50 });
