/**
 * Building and writing the generated snippet.
 *
 * Two things differ from the original implementation:
 *
 * 1. The dark and light passes are one function called twice, rather than two
 *    near-identical 100-line branches that drifted apart.
 * 2. The generated CSS is fenced, so anything a user hand-writes in the file
 *    outside the fences survives a save instead of being silently discarded.
 */
import { STYLE_CONTROLS, SHADOW_ELEMENTS } from '../schema';
import type { ShadowElementConfig, StyleControl } from '../schema';
import { scopeSelectors, scopeCssBlock, splitSelectorList, filterCssBlockToMode } from '../css/selectors';
import { computeShadowString, generateKeyframeBlock } from '../css/shadows';
import { generateCheckboxStyleRules } from '../css/checkbox';
import { generateGlassCss } from '../css/glass';
import { generateCalloutCss, CALLOUT_COLOR_GROUPS } from '../css/callouts';
import {
	generateCustomBackgroundCss,
	generateUIElementCss,
	isCompanionRuleActive,
} from '../css/ui-elements';
import type { ThemeTokenState } from '../css/ui-elements';

export type ThemeMode = '.theme-dark' | '.theme-light';

export const GENERATED_HEADER = '/* Generated by Obsidian CSS Snippet Designer */';

/** Markers delimiting the region this plugin owns. Everything outside is the user's. */
export const FENCE_BEGIN = '/* >>> css-snippet-designer:begin — generated block, edits inside are overwritten <<< */';
export const FENCE_END = '/* >>> css-snippet-designer:end <<< */';

/** Variable prefixes that are written even without an explicit enabled flag. */
const IMPLICIT_PREFIXES = [
	'--sh-',
	'--nav-box-',
	'--header-',
	'--h1-gradient-',
	'--h2-gradient-',
	'--h3-gradient-',
	'--h4-gradient-',
	'--h5-gradient-',
	'--h6-gradient-',
];

interface ModeContext {
	mode: ThemeMode;
	tokens: Map<string, string>;
	enabled: Map<string, boolean>;
	/** Suffix used when naming generated keyframes. */
	scopeKey: 'themedark' | 'themelight';
	defaultOutlineColor: string;
}

function contextFor(mode: ThemeMode, state: ThemeTokenState): ModeContext {
	return mode === '.theme-dark'
		? {
			mode,
			tokens: state.darkTokens,
			enabled: state.darkEnabled,
			scopeKey: 'themedark',
			defaultOutlineColor: '#7c3aed',
		}
		: {
			mode,
			tokens: state.lightTokens,
			enabled: state.lightEnabled,
			scopeKey: 'themelight',
			defaultOutlineColor: '#6d28d9',
		};
}

/** Index of every control that owns a custom property, for default comparisons. */
const CONTROL_BY_VARIABLE = new Map(STYLE_CONTROLS.map((c) => [c.variable, c] as const));

function stockDefaultFor(ctrl: StyleControl, mode: ThemeMode): string {
	return mode === '.theme-dark' ? ctrl.defaultDarkValue : ctrl.defaultLightValue;
}

/**
 * Whether a control still sits on the value the plugin ships as Obsidian's own.
 *
 * Writing such a value back pins Obsidian to what it already does, so the
 * declaration and any companion rule that reads it are pure weight in the
 * snippet. Toggles are deliberately excluded: `readable-line-length` and
 * `titlebar-match-unfocused` default to ON, and for those the companion rule
 * *is* the feature rather than a restatement of a stock value.
 */
function isAtStockDefault(ctrl: StyleControl, mode: ThemeMode, value: string | undefined): boolean {
	if (ctrl.type === 'toggle') return false;
	if (value === undefined) return true;
	return value === stockDefaultFor(ctrl, mode);
}

/** A companion rule earns its place in one theme when it is active AND not a restatement of stock. */
function shouldEmitCompanion(ctrl: StyleControl, state: ThemeTokenState, mode: ThemeMode): boolean {
	if (!isCompanionRuleActive(ctrl, state, mode)) return false;
	const tokens = mode === '.theme-dark' ? state.darkTokens : state.lightTokens;
	return !isAtStockDefault(ctrl, mode, tokens.get(ctrl.variable));
}

/** True when any of `variables` has been moved off the value the plugin ships as Obsidian's. */
function anyCustomised(state: ThemeTokenState, mode: ThemeMode, variables: readonly string[]): boolean {
	const tokens = mode === '.theme-dark' ? state.darkTokens : state.lightTokens;
	return variables.some((variable) => {
		const ctrl = CONTROL_BY_VARIABLE.get(variable);
		if (!ctrl) return false;
		return !isAtStockDefault(ctrl, mode, tokens.get(variable));
	});
}

const CHECKBOX_VARIABLES = [
	'--checkbox-style',
	'--checkbox-color',
	'--checkbox-border-color',
	'--checkbox-marker-color',
	'--checkbox-size',
	'--checkbox-radius',
] as const;

/**
 * Whether this theme needs the task-checkbox marker rules.
 *
 * The generator redraws Obsidian's own tick as a mask image so that marker
 * colour and size become adjustable. Left at stock that is a reproduction of
 * what Obsidian already draws, so it is only worth emitting once something
 * about the checkbox has actually been changed.
 */
export function emitsCheckboxStyling(state: ThemeTokenState, mode: ThemeMode): boolean {
	const enabled = mode === '.theme-dark' ? state.darkEnabled : state.lightEnabled;
	if (!(enabled.get('--checkbox-style') ?? true)) return false;
	return anyCustomised(state, mode, CHECKBOX_VARIABLES);
}

/**
 * Whether the settings-dialog toggle switches need their protective block.
 *
 * Its job is to stop the task-checkbox rules above from reaching Obsidian's
 * own settings toggles, and to keep those toggles on the accent colour. With
 * neither the checkbox rules nor a custom accent in play there is nothing to
 * protect them from, and Obsidian styles them correctly on its own.
 */
export function emitsToggleSwitchProtection(state: ThemeTokenState): boolean {
	const modes: ThemeMode[] = ['.theme-dark', '.theme-light'];
	return modes.some(
		(mode) => emitsCheckboxStyling(state, mode) || anyCustomised(state, mode, ['--text-accent'])
	);
}

/**
 * The per-type callout groups worth emitting for one theme.
 *
 * Every group's stock value is Obsidian's own accent for those callout types,
 * so restating it changes nothing.
 */
export function customisedCalloutGroups(state: ThemeTokenState, mode: ThemeMode): Map<string, boolean> {
	const enabled = mode === '.theme-dark' ? state.darkEnabled : state.lightEnabled;
	const filtered = new Map<string, boolean>();
	for (const group of CALLOUT_COLOR_GROUPS) {
		const on = (enabled.get(group.variable) ?? false) && anyCustomised(state, mode, [group.variable]);
		filtered.set(group.variable, on);
	}
	return filtered;
}

/**
 * Whether every declaration in a companion block takes its value from a `var()`.
 *
 * Such a block is inert wherever its tokens are not set, so confining it to the
 * theme that asked for it cannot change how the other theme renders. A block
 * that also states something flat - a `transition`, a `line-height`, a reset
 * like `background-image: none` - was doing that work in *both* themes, so it
 * keeps being emitted unscoped. Narrowing it would quietly change the theme
 * that never turned the feature on.
 */
function isPurelyTokenDriven(css: string): boolean {
	let depth = 0;
	let buffer = '';
	for (const char of css) {
		if (char === '{') {
			depth++;
			buffer = '';
			continue;
		}
		if (char === '}' || char === ';') {
			if (depth > 0 && buffer.includes(':') && !declarationFollowsAToken(buffer)) return false;
			if (char === '}') depth--;
			buffer = '';
			continue;
		}
		if (depth > 0) buffer += char;
	}
	return true;
}

function declarationFollowsAToken(declaration: string): boolean {
	const separator = declaration.indexOf(':');
	const property = declaration.slice(0, separator).trim();
	const value = declaration.slice(separator + 1);
	if (!property || /\s/.test(property)) return true; // not a declaration - a nested selector
	return value.includes('var(');
}

/**
 * The `/* Feature DOM Bindings *\/` section.
 *
 * Shared with the live preview in `view.ts` so the two can never disagree about
 * which bindings a design produces.
 *
 * Companion CSS is authored theme-agnostically and driven by theme-scoped
 * custom properties, so a rule needed by only one theme used to be emitted
 * unscoped and left to go inert in the other via its `var()` fallbacks. It is
 * now scoped to the theme that asked for it, which is both what the setting
 * says and one less rule for the other theme to match. A rule both themes want
 * is still emitted once, unscoped: scoping it twice would double the block for
 * no behavioural gain.
 */
export function buildCompanionBindings(state: ThemeTokenState): string {
	let out = '';
	for (const ctrl of STYLE_CONTROLS) {
		if (!ctrl.companionCss) continue;
		const darkOn = shouldEmitCompanion(ctrl, state, '.theme-dark');
		const lightOn = shouldEmitCompanion(ctrl, state, '.theme-light');
		if (!darkOn && !lightOn) continue;

		const body = ctrl.companionCss.trim();
		if (darkOn && lightOn) {
			out += `${body}\n`;
			continue;
		}
		const wanted: ThemeMode = darkOn ? '.theme-dark' : '.theme-light';
		// A block with its own `.theme-*` branches: keep the branch that was
		// asked for and drop the one restating stock.
		if (/\.theme-(dark|light)/.test(body)) {
			out += `${filterCssBlockToMode(wanted, body).trim()}\n`;
			continue;
		}
		// A block that also states things independent of its token was doing
		// that work in both themes, so narrowing it would change the theme that
		// never switched it on.
		if (!isPurelyTokenDriven(body)) {
			out += `${body}\n`;
			continue;
		}
		out += `${scopeCssBlock(wanted, body)}\n`;
	}
	return out;
}

/** The `.theme-dark { … }` / `.theme-light { … }` custom-property block. */
export function buildThemeTokenBlock(ctx: ModeContext, referenced?: ReadonlySet<string>): string {
	/**
	 * A custom property earns a line only if something will read it: either a
	 * rule in this snippet resolves it through `var()`, or it is a control whose
	 * value Obsidian itself consumes and the user has moved off stock. Writing
	 * the rest back declared values nothing looked at - the bulk of the file on
	 * a freshly reset design.
	 */
	const keep = (name: string): boolean => {
		if (!referenced) return true;
		if (referenced.has(name)) return true;
		const ctrl = CONTROL_BY_VARIABLE.get(name);
		if (!ctrl) return false;
		// A switched-off toggle nothing reads is just a record of being off.
		// A switched-on one is kept even when unread: some of these are
		// Obsidian's own properties (`--file-line-width`), where the "on" value
		// is the whole effect and dropping it would hand the pane back to
		// Obsidian's default width.
		if (ctrl.type === 'toggle') {
			return ctx.tokens.get(name) === (ctrl.toggleTrueValue ?? 'true');
		}
		return !isAtStockDefault(ctrl, ctx.mode, ctx.tokens.get(name));
	};

	let out = `${ctx.mode} {\n`;
	for (const [name, isEnabled] of ctx.enabled) {
		if (!isEnabled) continue;
		if (!keep(name)) continue;
		const value = ctx.tokens.get(name);
		if (value) out += `  ${name}: ${value};\n`;
	}
	for (const [name, value] of ctx.tokens) {
		if (ctx.enabled.has(name)) continue;

		if (!keep(name)) continue;

		if (name.startsWith('--ui-')) {
			if (name.startsWith('--ui-bg-')) {
				if (ctx.tokens.get('--ui-bg-enabled') === 'true') {
					out += `  ${name}: ${value};\n`;
				}
				continue;
			}
			if (name === '--ui-master-opacity') {
				if (value !== '1.0' && value !== '1') {
					out += `  ${name}: ${value};\n`;
				}
				continue;
			}
			if (name === '--ui-transition-duration') {
				if (value !== '0.25s' && value !== '0.25') {
					out += `  ${name}: ${value};\n`;
				}
				continue;
			}
			if (name === '--ui-global-hover-reveal') {
				if (value === 'true') {
					out += `  ${name}: ${value};\n`;
				}
				continue;
			}

			// Check per-element tokens: only emit if opacity is customized (< 1.0)
			const elMatch = name.match(/^--ui-([a-z0-9-]+)-(opacity|hover-reveal)$/);
			if (elMatch) {
				const elId = elMatch[1];
				const elOp = parseFloat(ctx.tokens.get(`--ui-${elId}-opacity`) ?? '1');
				if (!isNaN(elOp) && elOp < 1.0) {
					out += `  ${name}: ${value};\n`;
				}
				continue;
			}

			continue;
		}

		if (IMPLICIT_PREFIXES.some((p) => name.startsWith(p))) {
			out += `  ${name}: ${value};\n`;
		}
	}
	return `${out}}\n\n`;
}

/** Extra rules certain elements need so their shadow is not clipped. */
export function containmentFixes(id: string): string {
	switch (id) {
		case 'workspace-leaf-resizer-hover':
			return 'transition: box-shadow 0.15s ease 20ms, outline 0.15s ease 20ms, border-color 0.15s ease 20ms !important;\n  transition-delay: 20ms !important;\n  ';
		case 'active-leaf':
			return 'position: relative !important;\n  z-index: 2 !important;\n  ';
		case 'callouts':
			return 'position: relative !important;\n  z-index: 2 !important;\n  overflow: visible !important;\n  contain: none !important;\n  --callout-blend-mode: normal !important;\n  mix-blend-mode: normal !important;\n  isolation: auto !important;\n  margin-top: 12px !important;\n  margin-bottom: 12px !important;\n  ';
		case 'codeblocks':
			return 'position: relative !important;\n  overflow: visible !important;\n  contain: none !important;\n  ';
		case 'headings':
			return 'overflow: visible !important;\n  ';
		default:
			return '';
	}
}

/** Companion rules that must sit outside the element's own selector. */
export function overflowCompanions(id: string, mode: ThemeMode): string {
	if (id === 'workspace-leaf-resizer-hover') {
		return `${mode} .workspace-leaf-resize-handle:active,\n${mode} .workspace-split > hr:active,\n${mode} hr.workspace-split-hr:active {\n  transition-delay: 0s !important;\n}\n${mode} .workspace-leaf-resize-handle,\n${mode} .workspace-split > hr,\n${mode} hr.workspace-split-hr {\n  transition: box-shadow 0.15s ease, outline 0.15s ease, border-color 0.15s ease !important;\n}\n`;
	}
	if (id === 'headings') {
		return `${mode} .view-header-title-container,\n${mode} .view-header-title {\n  overflow: visible !important;\n}\n`;
	}
	if (id === 'callouts') {
		return `${mode} .cm-embed-block:has(> .callout),\n${mode} .cm-embed-block:has(.callout),\n${mode} .cm-embed-block.cm-callout,\n${mode} .cm-callout {\n  overflow: visible !important;\n  contain: none !important;\n  position: relative !important;\n  z-index: 2 !important;\n  margin-top: 12px !important;\n  margin-bottom: 12px !important;\n}\n${mode} .markdown-source-view.mod-cm6 .cm-embed-block:has(> .callout):hover,\n${mode} .markdown-source-view.mod-cm6 .cm-embed-block:has(.callout):hover,\n${mode} .markdown-source-view.mod-cm6 .cm-embed-block.cm-callout:hover,\n${mode} .cm-embed-block:has(> .callout):hover,\n${mode} .cm-embed-block.cm-callout:hover {\n  overflow: visible !important;\n  box-shadow: none !important;\n}\n`;
	}
	if (id === 'codeblocks') {
		return `${mode} .markdown-rendered div[class*="block-language-"],\n${mode} .markdown-rendered .code-block-wrap,\n${mode} .markdown-rendered pre:not([class*="block-language-"] pre):not(.code-block-wrap pre),\n${mode} .cm-embed-block:has(pre),\n${mode} .cm-embed-block:has(div[class*="block-language-"]) {\n  overflow: visible !important;\n  contain: none !important;\n}\n`;
	}
	return '';
}

/**
 * Shadow, outline and animation rules for one element in one theme.
 * `animatedSelectors` collects anything that ends up animated, so a
 * reduced-motion block can switch them all off in one place.
 */
function buildShadowRulesForElement(
	el: ShadowElementConfig,
	ctx: ModeContext,
	animatedSelectors: string[],
): string {
	const shadowOn = ctx.tokens.get(`--sh-${el.id}-enabled`) === 'true';
	const outlineOn = ctx.tokens.get(`--sh-${el.id}-outline-enabled`) === 'true';
	if (!shadowOn && !outlineOn) return '';

	let out = '';
	const animBlock = generateKeyframeBlock(el, ctx.tokens, ctx.scopeKey);
	if (animBlock) out += `${animBlock.css}\n`;

	// A static declaration needs !important to beat the theme; an animated one
	// must not carry it, or the animation cannot take effect.
	const imp = animBlock ? '' : ' !important';
	let body = '';

	if (shadowOn) {
		const shadow = computeShadowString(el.id, ctx.tokens, el.kind, 'base');
		body += el.kind === 'text'
			? `text-shadow: ${shadow}${imp};\n  `
			: `box-shadow: ${shadow}${imp};\n  `;
	}
	if (outlineOn && el.supportsOutline) {
		const width = ctx.tokens.get(`--sh-${el.id}-outline-width`) ?? '2px';
		const color = ctx.tokens.get(`--sh-${el.id}-outline-color`) ?? ctx.defaultOutlineColor;
		if (el.kind === 'text') {
			body += `-webkit-text-stroke: ${width} ${color}${imp};\n  `;
		} else {
			body += `outline: ${width} solid ${color}${imp};\n  outline-offset: -1px${imp};\n  `;
		}
	}
	if (animBlock) {
		const speed = ctx.tokens.get(`--sh-${el.id}-anim-speed`) ?? '2.5s';
		const timing = animBlock.timingFunction ?? 'ease-in-out';
		if (animBlock.hint) {
			body += `will-change: ${animBlock.hint};\n  backface-visibility: hidden;\n  `;
		}
		body += `animation: ${animBlock.keyframeName} ${speed} ${timing} infinite !important;\n  `;
	}
	body += containmentFixes(el.id);

	const selector = scopeSelectors(ctx.mode, el.selector);
	if (animBlock) animatedSelectors.push(selector);
	out += `${selector} {\n  ${body.trim()}\n}\n`;
	out += overflowCompanions(el.id, ctx.mode);

	if (el.id === 'active-leaf' && outlineOn && ctx.tokens.get('--glass-enabled') !== 'true') {
		const width = ctx.tokens.get(`--sh-${el.id}-outline-width`) ?? '2px';
		const color = ctx.tokens.get(`--sh-${el.id}-outline-color`) ?? ctx.defaultOutlineColor;
		out += `${ctx.mode} .workspace-split.mod-root .workspace-tab-header-container .workspace-tab-header.is-active::before,\n${ctx.mode} .workspace-split.mod-root .workspace-tab-header-container .workspace-tab-header.is-active::after {\n  box-shadow: inset 0 0 0 ${width} ${color}, 0 0 0 calc(var(--tab-curve, 6px) * 4) var(--tab-background-active) !important;\n}\n`;
	}
	return out;
}

/**
 * Turn every infinite animation off for readers who ask for reduced motion.
 *
 * Emitted as one trailing block rather than by wrapping each generator, so the
 * rule stays additive and cannot change the non-reduced-motion output.
 */
export function buildReducedMotionBlock(selectors: string[]): string {
	if (selectors.length === 0) return '';
	const unique = Array.from(new Set(selectors));
	return (
		'\n/* Respect the reader\'s reduced-motion preference. */\n' +
		'@media (prefers-reduced-motion: reduce) {\n' +
		unique.map((s) => `  ${s.split(',\n').join(',\n  ')}`).join(',\n') +
		' {\n    animation: none !important;\n    transition: none !important;\n  }\n}\n'
	);
}

/** Compose the full generated stylesheet from the current token state. */
export function buildGeneratedCss(state: ThemeTokenState): string {
	const modes: ThemeMode[] = ['.theme-dark', '.theme-light'];
	const contexts = modes.map((m) => contextFor(m, state));
	const animatedSelectors: string[] = [];

	// The rules are built first so the custom-property blocks can be narrowed to
	// the properties those rules actually resolve. Everything else declared a
	// value nothing read.
	let css = '';

	css += '/* Feature DOM Bindings */\n';
	css += buildCompanionBindings(state);

	css += '\n/* Task Checkbox Marker Styles */\n';
	for (const ctx of contexts) {
		if (emitsCheckboxStyling(state, ctx.mode)) {
			css += generateCheckboxStyleRules(ctx.mode, ctx.tokens);
		}
	}

	css += '\n/* Callout Accent Colors */\n';
	for (const ctx of contexts) {
		css += generateCalloutCss(ctx.mode, ctx.tokens, customisedCalloutGroups(state, ctx.mode));
	}

	css += '\n/* Shadows, Glows & Outlines Overrides */\n';
	for (const el of SHADOW_ELEMENTS) {
		for (const ctx of contexts) {
			css += buildShadowRulesForElement(el, ctx, animatedSelectors);
		}
	}

	for (const ctx of contexts) css += generateGlassCss(ctx.mode, ctx.tokens);

	css += '\n/* Custom Backgrounds & Canvas Patterns */\n';
	for (const ctx of contexts) css += generateCustomBackgroundCss(ctx.mode, state, animatedSelectors);

	css += '\n/* UI Elements Opacity & Minimalist Layout Overrides */\n';
	for (const ctx of contexts) css += generateUIElementCss(ctx.mode, state);

	// Emitted while any control is on: it does not restate an Obsidian default,
	// it removes the frame Obsidian draws in frameless mode. Gated on an active
	// design so a full reset leaves the file empty and the vault falls back to
	// the user's own theme.
	const anythingEnabled =
		[...state.darkEnabled.values()].some(Boolean) ||
		[...state.lightEnabled.values()].some(Boolean);
	if (anythingEnabled) {
		css += '\n/* Seamless Frameless Window Titlebar */\n';
		css += `.is-hidden-frameless .titlebar {\n` +
			`  border: none !important;\n` +
			`  background: transparent !important;\n` +
			`}\n`;
	}

	if (emitsToggleSwitchProtection(state)) {
	css += '\n/* Settings & UI Toggle Switches */\n';
	css += `.checkbox-container input[type="checkbox"] {\n` +
		`  position: absolute !important;\n` +
		`  opacity: 0 !important;\n` +
		`  pointer-events: none !important;\n` +
		`  width: 0 !important;\n` +
		`  height: 0 !important;\n` +
		`  margin: 0 !important;\n` +
		`  padding: 0 !important;\n` +
		`  border: none !important;\n` +
		`  background: transparent !important;\n` +
		`  outline: none !important;\n` +
		`  box-shadow: none !important;\n` +
		`  appearance: none !important;\n` +
		`  -webkit-appearance: none !important;\n` +
		`}\n` +
		`.checkbox-container input[type="checkbox"]::before,\n` +
		`.checkbox-container input[type="checkbox"]::after {\n` +
		`  display: none !important;\n` +
		`  content: none !important;\n` +
		`  mask-image: none !important;\n` +
		`  -webkit-mask-image: none !important;\n` +
		`}\n` +
		`.modal.mod-settings .checkbox-container,\n` +
		`.mod-settings .checkbox-container,\n` +
		`.vertical-tab-content .checkbox-container {\n` +
		`  background-color: var(--text-accent) !important;\n` +
		`  border-color: var(--text-accent) !important;\n` +
		`  transition: background-color 0.15s ease, border-color 0.15s ease;\n` +
		`}\n` +
		`.modal.mod-settings .checkbox-container:hover,\n` +
		`.mod-settings .checkbox-container:hover,\n` +
		`.vertical-tab-content .checkbox-container:hover {\n` +
		`  background-color: var(--interactive-accent-hover, var(--text-accent)) !important;\n` +
		`  border-color: var(--interactive-accent-hover, var(--text-accent)) !important;\n` +
		`  filter: brightness(1.12);\n` +
		`}\n` +
		`.modal.mod-settings .checkbox-container:after,\n` +
		`.modal.mod-settings .checkbox-container::after,\n` +
		`.mod-settings .checkbox-container:after,\n` +
		`.mod-settings .checkbox-container::after,\n` +
		`.vertical-tab-content .checkbox-container:after,\n` +
		`.vertical-tab-content .checkbox-container::after {\n` +
		`  transition: transform 0.15s ease-in-out, width 0.15s ease-in-out, background-color 0.15s ease-in-out;\n` +
		`}\n` +
		`.modal.mod-settings .checkbox-container:not(.is-enabled),\n` +
		`.mod-settings .checkbox-container:not(.is-enabled),\n` +
		`.vertical-tab-content .checkbox-container:not(.is-enabled) {\n` +
		`  background-color: var(--text-accent) !important;\n` +
		`  border-color: var(--text-accent) !important;\n` +
		`  --toggle-thumb-color: rgba(0, 0, 0, 0.45);\n` +
		`}\n` +
		`.modal.mod-settings .checkbox-container:not(.is-enabled):after,\n` +
		`.modal.mod-settings .checkbox-container:not(.is-enabled)::after,\n` +
		`.mod-settings .checkbox-container:not(.is-enabled):after,\n` +
		`.mod-settings .checkbox-container:not(.is-enabled):after,\n` +
		`.vertical-tab-content .checkbox-container:not(.is-enabled):after,\n` +
		`.vertical-tab-content .checkbox-container:not(.is-enabled)::after {\n` +
		`  background-color: rgba(0, 0, 0, 0.45) !important;\n` +
		`  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.35) !important;\n` +
		`}\n` +
		`.modal.mod-settings .checkbox-container.is-enabled,\n` +
		`.mod-settings .checkbox-container.is-enabled,\n` +
		`.vertical-tab-content .checkbox-container.is-enabled {\n` +
		`  background-color: var(--text-accent) !important;\n` +
		`  border-color: var(--text-accent) !important;\n` +
		`  --toggle-thumb-color: var(--text-on-accent, #ffffff);\n` +
		`}\n` +
		`.modal.mod-settings .checkbox-container.is-enabled:after,\n` +
		`.modal.mod-settings .checkbox-container.is-enabled::after,\n` +
		`.mod-settings .checkbox-container.is-enabled:after,\n` +
		`.mod-settings .checkbox-container.is-enabled:after,\n` +
		`.vertical-tab-content .checkbox-container.is-enabled:after,\n` +
		`.vertical-tab-content .checkbox-container.is-enabled::after {\n` +
		`  background-color: var(--text-on-accent, #ffffff) !important;\n` +
		`}\n`;
	}

	css += buildReducedMotionBlock(animatedSelectors);

	let head = `${GENERATED_HEADER}\n\n`;
	for (const ctx of contexts) {
		head += buildThemeTokenBlock(ctx, collectReferencedProperties(css, ctx.mode));
	}
	return head + css;
}

/**
 * The custom properties the finished rules resolve through `var()` *in one
 * theme*.
 *
 * A rule scoped to `.theme-light` can never resolve anything while the dark
 * theme is on, so the colours it reads have no business in the dark block.
 * Counting references across the whole sheet made each theme carry the other
 * one's variables - on a design where only one theme has been touched, that was
 * the entire remaining cost of the untouched one.
 *
 * A rule that names neither theme applies to both, and so does anything outside
 * a rule (keyframes in particular), which is the conservative answer.
 */
export function collectReferencedProperties(css: string, mode: ThemeMode): ReadonlySet<string> {
	const other: ThemeMode = mode === '.theme-dark' ? '.theme-light' : '.theme-dark';
	const found = new Set<string>();

	const add = (text: string): void => {
		for (const match of text.matchAll(/var\(\s*(--[A-Za-z0-9_-]+)/g)) {
			const name = match[1];
			if (name) found.add(name);
		}
	};

	let prelude = '';
	let body = '';
	let depth = 0;
	for (const char of css) {
		if (depth === 0) {
			if (char === '{') {
				depth = 1;
				body = '';
			} else {
				prelude += char;
			}
			continue;
		}
		if (char === '{') depth++;
		if (char === '}') {
			depth--;
			if (depth === 0) {
				if (appliesInMode(prelude, mode, other)) add(body);
				prelude = '';
				body = '';
				continue;
			}
		}
		body += char;
	}
	// Anything after the last closing brace belongs to no rule; count it.
	add(prelude);
	return found;
}

/** A rule reaches `mode` unless every one of its selectors is scoped to the other theme. */
function appliesInMode(prelude: string, mode: ThemeMode, other: ThemeMode): boolean {
	const selectors = splitSelectorList(prelude.replace(/\/\*[\s\S]*?\*\//g, ''));
	if (selectors.length === 0) return true;
	return !selectors.every((selector) => selector.includes(other) && !selector.includes(mode));
}

/**
 * Splice `generated` into `existing`, preserving anything the user wrote
 * outside the fences.
 *
 * - Fenced file: the fenced region is replaced, everything else is kept.
 * - Unfenced file produced by an older build: replaced wholesale, since all of
 *   it was generated.
 * - Any other file: kept in full, with the generated block appended, so a
 *   snippet the user wrote by hand is never destroyed.
 */
export function mergeIntoExisting(existing: string | null, generated: string): string {
	const fenced = `${FENCE_BEGIN}\n${generated.trimEnd()}\n${FENCE_END}\n`;
	if (existing === null || existing.trim() === '') return fenced;

	// First BEGIN to LAST END, so a file that somehow ended up with two generated
	// blocks collapses back to one instead of preserving the stale copy forever as
	// "user content", where its !important rules would fight the live ones.
	// Identical to indexOf for a well-formed single-block file.
	const begin = existing.indexOf(FENCE_BEGIN);
	const end = existing.lastIndexOf(FENCE_END);
	if (begin !== -1 && end !== -1 && end > begin) {
		const before = existing.slice(0, begin);
		const after = existing.slice(end + FENCE_END.length).replace(/^\n/, '');
		return `${before}${fenced}${after}`;
	}

	if (existing.trimStart().startsWith(GENERATED_HEADER)) return fenced;

	return `${existing.trimEnd()}\n\n${fenced}`;
}
